# Generated by Django 5.2.8 on 2025-12-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Mailing recipient', 'verbose_name_plural': 'Mailing recipients'},
        ),
        migrations.AlterField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, null=True, verbose_name='name'),
        ),
    ]
