# Generated by Django 5.2.8 on 2025-12-03 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['name_message'], 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['message'], 'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
        migrations.AlterField(
            model_name='message',
            name='description_message',
            field=models.CharField(verbose_name='body of the letter'),
        ),
        migrations.AlterField(
            model_name='message',
            name='name_message',
            field=models.CharField(verbose_name='subject of the letter'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='end_time',
            field=models.DateTimeField(verbose_name='mailing end time'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='start_time',
            field=models.DateTimeField(verbose_name='mailing start time'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('launched', 'Launched'), ('completed', 'Completed')], verbose_name='mailing status'),
        ),
    ]
