# Generated by Django 5.2.8 on 2025-12-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_alter_message_options_alter_newsletter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('launched', 'Launched'), ('completed', 'Completed')], default='created', verbose_name='mailing status'),
        ),
    ]
