# Generated by Django 5.2.8 on 2025-12-24 17:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0005_mailingattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletter',
            name='recipients',
        ),
        migrations.AddField(
            model_name='newsletter',
            name='recipients',
            field=models.ManyToManyField(related_name='newsletters', to=settings.AUTH_USER_MODEL, verbose_name='пользователи'),
        ),
    ]
